services:
  api:
    build: .
    container_name: inventory-management-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/inventory_management
      JWT_ACCESS_SECRET: docker_access_token_secret
      JWT_ACCESS_EXPIRES_IN: 15m
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: inventory-management-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: