const errorCodes = Object.freeze({
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INACTIVE_PRODUCT: "INACTIVE_PRODUCT",
  INACTIVE_WAREHOUSE: "INACTIVE_WAREHOUSE",
  INACTIVE_STOCK: "INACTIVE_STOCK",
  INVALID_CORRELATION_ID: "INVALID_CORRELATION_ID",
  INVALID_IDEMPOTENCY_KEY: "INVALID_IDEMPOTENCY_KEY",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  IDEMPOTENCY_RESPONSE_TOO_LARGE: "IDEMPOTENCY_RESPONSE_TOO_LARGE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  STALE_VERSION: "STALE_VERSION",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
});

module.exports = errorCodes;
